/**
 * @see https://github.com/EvanLi/Github-Ranking/blob/6a1e41a45fc467d3e9b0f09cbdff2450807e95a6/source/process.py#L12
 */
export enum Languages {
  ActionScript = 'ActionScript',
  C = 'C',
  CSharp = 'CSharp',
  CPP = 'CPP',
  Clojure = 'Clojure',
  CoffeeScript = 'CoffeeScript',
  CSS = 'CSS',
  Dart = 'Dart',
  DM = 'DM',
  Elixir = 'Elixir',
  Go = 'Go',
  Groovy = 'Groovy',
  Haskell = 'Haskell',
  HTML = 'HTML',
  Java = 'Java',
  JavaScript = 'JavaScript',
  Julia = 'Julia',
  Kotlin = 'Kotlin',
  Lua = 'Lua',
  MATLAB = 'MATLAB',
  ObjectiveC = 'Objective-C',
  Perl = 'Perl',
  PHP = 'PHP',
  PowerShell = 'PowerShell',
  Python = 'Python',
  R = 'R',
  Ruby = 'Ruby',
  Rust = 'Rust',
  Scala = 'Scala',
  Shell = 'Shell',
  Swift = 'Swift',
  TeX = 'TeX',
  TypeScript = 'TypeScript',
  VimScript = 'Vim-script',
}
